---
- name: Converge
  hosts: all
  tasks:
    - name: Install OpenHPC repository
      yum:
        name: "https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm"
        state: present
    - name: "Include ansible-role-openhpc"
      include_role:
        name: "ansible-role-openhpc/"
      vars:
        openhpc_enable:
          control: "{{ inventory_hostname in groups['testohpc_login'] }}"
          batch: "{{ inventory_hostname in groups['testohpc_compute'] }}"
          runtime: true
        openhpc_slurm_service_enabled: true
        openhpc_slurm_control_host: "{{ groups['testohpc_login'] | first }}"
        openhpc_slurm_partitions:
          - name: "compute"
        openhpc_cluster_name: testohpc

