---
name: single partition, group is partition
driver:
  name: docker
platforms:
  - name: testohpc-login-0
<<<<<<< HEAD
    image: ${MOLECULE_IMAGE}
    #pre_build_image: true
=======
    image: docker.io/pycontribs/${MOLECULE_IMAGE}
    pre_build_image: true
>>>>>>> add centos8 travis tests
    groups:
      - testohpc_login
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
  - name: testohpc-compute-0
<<<<<<< HEAD
    image: ${MOLECULE_IMAGE}
    #pre_build_image: true
=======
    image: docker.io/pycontribs/${MOLECULE_IMAGE}
    pre_build_image: true
>>>>>>> add centos8 travis tests
    groups:
      - testohpc_compute
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
  - name: testohpc-compute-1
<<<<<<< HEAD
    image: ${MOLECULE_IMAGE}
    #pre_build_image: true
=======
    image: docker.io/pycontribs/${MOLECULE_IMAGE}
    pre_build_image: true
>>>>>>> add centos8 travis tests
    groups:
      - testohpc_compute
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - name: net1
provisioner:
  name: ansible
verifier:
  name: ansible
