---
language: python

# Use the new container infrastructure
sudo: required
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - python3 -m pip install ansible
  - python3 -m pip install ansible-lint
  - python3 -m pip install molecule
  - python3 -m pip install docker

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Compensate for repo name being different to the role
  - ln -s $(pwd) ../stackhpc.openhpc

env:
  - SCENARIO=test1
  - SCENARIO=test1b
  - SCENARIO=test1c
  - SCENARIO=test2
  - SCENARIO=test3

script:
  # Run molecule tests
  - molecule test -s $SCENARIO

jobs:
  include:
    - stage: checks
      # Basic role syntax check
      script:
        - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
        # Run Ansible lint against the role
        - ansible-lint .
        # Test the custom filters
        - ansible-playbook tests/filter.yml -i tests/inventory -i tests/inventory-mock-groups

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
