---
- name: Install OpenHPC compute image packages
  yum:
    name: "@ohpc-base-compute"
    state: present

- name: Install OpenHPC SLURM client packages
  yum:
    name: "@ohpc-slurm-client"
    state: present

- name: Select the SLURM service to control
  set_fact:
    openhpc_slurm_service: slurmd

