---
- name: Install OpenHPC compute image packages
  package:
    name: "{{ ohpc_slurm_compute_packages }}"
    state: present

- name: Select the SLURM service to control
  set_fact:
    openhpc_slurm_service: slurmd

