---
# all tasks here are taken from runtime.yml - see bottom of file for what has been moved elsewhere
- name: Fail if openhpc_slurm_control_host or openhpc_cluster_name or openhpc_slurm_partitions are undefined
  fail:
    msg: "Undefined openhpc_slurm_control_host or openhpc_cluster_name or openhpc_slurm_partitions."
  when:
    openhpc_slurm_control_host == none or
    openhpc_cluster_name == none or
    openhpc_slurm_partitions | length == 0

- name: Ensure the Slurm spool directory exists
  file:
    path: /var/spool/slurm
    owner: slurm
    group: slurm
    mode: 0755
    state: directory

- name: Ensure the Munge service is enabled
  service:
    name: munge
    enabled: "{{ openhpc_slurm_service_enabled | bool }}"
  notify:
    - Restart Munge service

- name: Ensure munge config directory exists & world-readable
  file:
    path: "{{ openhpc_munge_key.location | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  run_once: "{{ openhpc_munge_key.shared_fs | bool }}"

- name: Generate a Munge key for the platform
  command: "dd if=/dev/urandom of={{ openhpc_munge_key.location }} bs=1 count=1024"
  args:
    creates: "{{ openhpc_munge_key.location }}"
  when: inventory_hostname == openhpc_slurm_control_host
  notify: Restart Munge service
  register: write_munge_key

- name: Set fact to trigger restart of munged on all hosts
  include_tasks: trigger-restart-munged.yml
  when:
    - write_munge_key is defined
    - write_munge_key is changed
    - openhpc_slurm_conf.shared_fs | bool
    - inventory_hostname == openhpc_slurm_control_host

- name: Restart all daemons using networked configuration
  command: /bin/true
  changed_when: true
  notify: Restart Munge service
  when:
    - restart_munged is defined
    - restart_munged | bool

- name: Retrieve Munge key from Slurm control host
  slurp:
    src: "{{ openhpc_munge_key.location }}"
  register: slurm_munge_key
  when: inventory_hostname == openhpc_slurm_control_host

- name: Write Munge key (if not networked)
  copy:
    content: "{{ hostvars[openhpc_slurm_control_host]['slurm_munge_key']['content'] | b64decode }}"
    dest: "{{ openhpc_munge_key.location }}"
    owner: munge
    group: munge
    mode: 0400
  when:
    - inventory_hostname != openhpc_slurm_control_host
    - not openhpc_munge_key.shared_fs | bool
  notify: Restart Munge service

- name: Assert Munge key permissions
  # This is necessary if the key was generated using dd
  file:
    path: "{{ openhpc_munge_key.location }}"
    owner: munge
    group: munge
    mode: 0400
  run_once: "{{ openhpc_munge_key.shared_fs | bool }}"

- name: Wait for network filesystem mount before munge daemon start
  block:
    - name: make drop-in directory
      file:
        path: "/etc/systemd/system/munge.service.d/"
        state: directory
        mode: 0700
    - name: Add drop-in to modify munge daemon unit parameters
      copy:
        dest: "/etc/systemd/system/munge.service.d/slurmconf.conf"
        content: |
          [Unit]
          RequiresMountsFor={{ openhpc_munge_key.location }}
          [Service]
          ExecStart=
          ExecStart=/usr/sbin/munged --syslog --key-file {{ openhpc_munge_key.location }}
        mode: 0600
      notify:
        - Reload systemd config
        - Restart Munge service
  when: "openhpc_munge_key.shared_fs or (openhpc_munge_key.location != '/etc/munge/munge.key')"

- name: Configure the slurm daemons
  include_tasks: configure-slurm.yml
  when: item.enabled
  vars:
    openhpc_slurm_service: "{{ item.service }}"
  with_items:
    - service: slurmctld
      enabled: "{{ openhpc_enable.control }}"
    - service: slurmd
      enabled: "{{ openhpc_enable.batch }}"

- name: Configure the slurm database service
  include_tasks: configure-slurmdbd.yml
  when: openhpc_enable.database

# tasks in runtime.yml which aren't here:
# - name: Ensure selected OpenHPC packages are installed => done by install action now
# - name: Install OpenHPC LMOD => done by install (separate task not in package list - why??)
# - name: Flush handlers => no longer reqd
# - name: Ensure Munge services are enabled and started => now done by start action
# - name: Ensure Slurm services are running => now done by start action
