---

- name: Ensure slurmdbd is enabled
  service:
    name: slurmdbd
    enabled: "{{ openhpc_slurm_service_enabled | bool }}"

- name: Template slurmdbd.conf
  template:
    src: slurmdbd.conf.j2
    dest: /etc/slurm/slurmdbd.conf
    mode: "0600"
    owner: root
    group: root
  notify: Restart slurmdbd service
  become: true
