- name: Install required slurm packages
  yum:
    name: "{{ item.value }}" # list of packages - ok after 2.0
  loop: "{{ openhpc_slurm_packages | dict2items }}"
  when: "openhpc_enable.get(item.key, false) | bool"

- name: Install packages from openhpc_packages variable
  yum:
    name: "{{ openhpc_packages }}"
  when: "openhpc_enable.runtime  | default(false) | bool"
