---
- include: control.yml
  when: openhpc_enable.control | default(false) | bool

- include: compute.yml
  when: openhpc_enable.batch | default(false) | bool

- include: runtime.yml
  when: openhpc_enable.runtime | default(false) | bool

- include: drain.yml
  when: openhpc_enable.drain | default(false) | bool

- include: resume.yml
  when: openhpc_enable.resume | default(false) | bool
...
