---

- name: Set slurm node type # NB defaults to login due to default var
  set_fact:
    openhpc_slurm_nodetype: "{{ item }}"
  loop: ['control', 'batch']
  when: "openhpc_enable[item] | default(false) | bool"

- include_tasks: "{{ openhpc_action }}.yml"
  loop: "{{ query('items', openhpc_actions) }}" # ensures a list even if passed a single item
  loop_control:
    loop_var: openhpc_action

# - include: runtime.yml
#   when: openhpc_enable.runtime | default(false) | bool

# - include: drain.yml
#   when: openhpc_enable.drain | default(false) | bool
#   delegate_to: "{{ openhpc_slurm_control_host }}"

# - include: resume.yml
#   when: openhpc_enable.resume | default(false) | bool
#   delegate_to: "{{ openhpc_slurm_control_host }}"
...
