---

# Validate package facts and include version-specific config
- name: Gather package facts
  package_facts:
    manager: rpm

- name: Check ohpc-release package is installed
  assert:
    that: "'ohpc-release' in ansible_facts.packages"
    quiet: yes
    fail_msg: |
      "The OpenHPC distro package should be installed in the image.
       Please see http://openhpc.community/downloads/"

- name: Include variables for OpenHPC version
  include_vars:
    file: "ohpc-{{ ansible_facts.packages['ohpc-release'][0]['version'] }}"

- include: control.yml
  when: openhpc_enable.control | default(false) | bool

- include: compute.yml
  when: openhpc_enable.batch | default(false) | bool

- include: database.yml
  when: openhpc_enable.database | default(false) | bool

- include: runtime.yml
  when: openhpc_enable.runtime | default(false) | bool

- include: post.yml
  when: openhpc_enable.runtime | default(false) | bool
  delegate_to: "{{ openhpc_slurm_control_host }}"

- include: drain.yml
  when: openhpc_enable.drain | default(false) | bool
  delegate_to: "{{ openhpc_slurm_control_host }}"

- include: resume.yml
  when: openhpc_enable.resume | default(false) | bool
  delegate_to: "{{ openhpc_slurm_control_host }}"
...
