---
- include: control.yml
  when: openhpc_enable.control | bool

- include: compute.yml
  when: openhpc_enable.batch | bool

- include: runtime.yml
  when: openhpc_enable.runtime | bool

- include: drain.yml
  when: openhpc_enable.drain | bool

- include: resume.yml
  when: openhpc_enable.resume | bool
...
