---

- name: Set slurm node type
  set_fact:
    slurm_nodetype: "{{ item }}"
  loop: "{{ openhpc_typevars.keys() }}"
  when: "openhpc_enable[item] | default(false) | bool"

- include_tasks: "{{ openhpc_action }}.yml"
  loop: "{{ openhpc_actions }}"
  loop_control:
    loop_var: openhpc_action

# - include: runtime.yml
#   when: openhpc_enable.runtime | default(false) | bool

# - include: drain.yml
#   when: openhpc_enable.drain | default(false) | bool
#   delegate_to: "{{ openhpc_slurm_control_host }}"

# - include: resume.yml
#   when: openhpc_enable.resume | default(false) | bool
#   delegate_to: "{{ openhpc_slurm_control_host }}"
...
