---

# Validate package facts and include version-specific config
- name: Gather package facts
  package_facts:
    manager: rpm
  tags: always

- name: Check ohpc-release package is installed
  assert:
    that: "'ohpc-release' in ansible_facts.packages"
    quiet: yes
    fail_msg: |
      "The OpenHPC distro package should be installed in the image.
       Please see http://openhpc.community/downloads/"

- name: Include variables for OpenHPC version
  include_vars:
    file: "ohpc-{{ ansible_facts.packages['ohpc-release'][0]['version'] }}"
  tags: always

- name: Select slurm service to control
  set_fact:
    openhpc_slurm_service: "{{ ohpc_slurm_services[item] }}"
  loop: "{{ ohpc_slurm_services.keys() | list }}"
  when: "openhpc_enable.get(item, false)"
  tags: always

- name: Install OpenHPC packages
  include_tasks:
    file: install.yml
    apply:
      tags: install
  tags: install

- name: Configure and enable Slurm
  include_tasks:
    file: runtime.yml
    apply:
      tags: configure
  when:
    - openhpc_enable.runtime | default(false) | bool
  tags:
    - configure

- include: drain.yml
  when: openhpc_enable.drain | default(false) | bool
  delegate_to: "{{ openhpc_slurm_control_host }}"

- include: resume.yml
  when: openhpc_enable.resume | default(false) | bool
  delegate_to: "{{ openhpc_slurm_control_host }}"
...
