---
- name: Fail if slurm_control_host or slurm_cluster_name or slurm_partitions are undefined
  fail:
    msg: "Undefined slurm_control_host or slurm_cluster_name or slurm_partitions."
  when:
    slurm_control_host == none or
    slurm_cluster_name == none or
    slurm_partitions | length == 0

- name: Install OpenHPC runtime Slurm packages
  yum:
    name:
      - "slurm-ohpc"
      - "munge-ohpc"
      - "slurm-slurmd-ohpc"
      - "slurm-example-configs-ohpc"
    state: installed

- name: Ensure the SLURM spool directory exists
  file:
    path: /var/spool/slurm
    owner: slurm
    group: slurm
    mode: 0755
    state: directory

- name: Ensure the Munge service is enabled
  service:
    name: munge
    enabled: "{{ slurm_service_enabled | bool }}"
  notify:
    - Restart Munge service

- name: Generate a Munge key for the platform
  command: "dd if=/dev/urandom of=/etc/munge/munge.key bs=1 count=1024"
  args:
    creates: "/etc/munge/munge.key"
  when: inventory_hostname == slurm_control_host

- name: Retrieve Munge key from Slurm control host
  slurp:
    src: "/etc/munge/munge.key"
  register: slurm_munge_key
  when: inventory_hostname == slurm_control_host

- name: Write Munge key
  copy:
    content: "{{ hostvars[slurm_control_host]['slurm_munge_key']['content'] | b64decode }}"
    dest: "/etc/munge/munge.key"
    owner: munge
    group: munge
    mode: 0400
  notify:
    - Restart Munge service

- name: Ensure SLURM services are enabled
  service:
    name: "{{ slurm_service }}"
    enabled: "{{ slurm_service_enabled | bool }}"
  notify:
    - Restart SLURM service

- name: Apply customised SLURM configuration
  template:
    src: slurm.conf.j2
    dest: /etc/slurm/slurm.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart SLURM service

- name: Flush handlers
  meta: flush_handlers

# In case the service isn't running and the config hasn't changed to trigger
# the handler, ensure it's running here.
- name: Ensure SLURM services are running
  service:
    name: "{{ slurm_service }}"
    state: "{{ 'started' if slurm_service_enabled | bool else 'stopped' }}"

# Install OpenHPC runtime
- name: Ensure selected OpenHPC packages are installed
  yum:
    name: "{{ openhpc_packages }}"
    state: present
...
