---
# Perform a reconfigure of slurm which does not requires restart of daemons, i.e. any changes except
# those listed in tasks/hard_reconfigure.yml. This avoids interrupting the scheduler.
# This does not rewrite slurm.conf - do that first
# NB: This requires communication between the daemons so if that is broken use hard_reconfigure
- name: reconfigure slurm
  command: scontrol reconfigure
  run_once: true
