---
- name: Ensure Munge services are enabled and started
  service:
    name: munge
    enabled: "{{ openhpc_slurm_service_enabled | bool }}"
    state: "{{ 'started' if openhpc_slurm_service_enabled | bool else 'stopped' }}"

- name: Ensure Slurm services are running
  service:
    name: "{{ openhpc_slurm_service }}"
    enabled: "{{ openhpc_slurm_service_enabled | bool }}"
    state: "{{ 'started' if openhpc_slurm_service_enabled | bool else 'stopped' }}"
