---
- name: Reload systemd config
  systemd:
    daemon_reload: yes
  when:
    - "'start' in openhpc_actions"

# NOTE: We need this running before slurmdbd
- name: Restart Munge service
  service:
    name: "munge"
    state: restarted
  when:
    - openhpc_slurm_service_enabled | bool
    - "'start' in openhpc_actions"

# NOTE: we need this running before slurmctld start
- name: Restart slurmdbd service
  service:
    name: "slurmdbd"
    state: restarted
  delegate_to: "{{ openhpc_slurmdbd_host }}"
  when:
    - openhpc_slurmdbd_host is defined
    - "'start' in openhpc_actions"
  run_once: true
  become: true

# NOTE: Allows you to restart slurmctld from another host
- name: Restart slurmctld service
  service:
    name: "slurmctld"
    state: restarted
  become: true
  delegate_to: "{{ openhpc_slurm_control_host }}"
  run_once: true
  when:
    - openhpc_slurm_service_enabled | bool
    - openhpc_reconfigure_mode == "hard"
    - "'start' in openhpc_actions"

- name: Restart slurmd service
  service:
    name: "slurmd"
    state: restarted
  delegate_to: "{{ openhpc_slurmdbd_host }}"
  when:
    - openhpc_enable.batch
    - openhpc_reconfigure_mode == "hard"
    - "'start' in openhpc_actions"
  become: true

- name: Reconfigure slurm
  command: scontrol reconfigure
  run_once: true
  listen:
    - Restart slurmdbd service
    - Restart slurmd service
  when:
    - openhpc_reconfigure_mode == "soft"
    - "'start' in openhpc_actions"
  failed_when: false
