---
- name: Restart SLURM service
  service:
    name: "{{slurm_service}}"
    state: reloaded
  when: slurm_service_enabled | bool

- name: Restart Munge service
  service:
    name: "munge"
    state: restarted
  when: slurm_service_enabled | bool
