---
- name: Reload systemd config
  systemd:
    daemon_reload: yes
  become: true
  when:
    - "'start' in openhpc_actions"

# NOTE: We need this running before slurmdbd
- name: Restart Munge service
  service:
    name: "munge"
    state: restarted
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all'] }}"
  run_once: true
  become: true
  when:
    - openhpc_slurm_service_enabled | bool
    - "'start' in openhpc_actions"

# NOTE: we need this running before slurmctld start
- name: Restart slurmdbd service
  service:
    name: "slurmdbd"
    state: restarted
  delegate_to: "{{ item }}"
  with_items: "{{ groups['openhpc_enable_database_True'] }}"
  when:
    - "'start' in openhpc_actions"
  run_once: true
  become: true

# NOTE: Allows you to restart slurmctld from another host
- name: Restart slurmctld service
  service:
    name: "slurmctld"
    state: restarted
  become: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['openhpc_enable_control_True'] }}"
  run_once: true
  when:
    - openhpc_slurm_service_enabled | bool
    - openhpc_reconfigure_mode == "hard"
    - "'start' in openhpc_actions"

- name: Restart slurmd service
  service:
    name: "slurmd"
    state: restarted
  delegate_to: "{{ item }}"
  with_items: "{{ groups['openhpc_enable_batch_True'] }}"
  run_once: True
  when:
    - openhpc_reconfigure_mode == "hard"
    - "'start' in openhpc_actions"
  become: true

- name: Reconfigure slurm
  command: scontrol reconfigure
  run_once: true
  delegate_to: "{{ item }}"
  with_items: "{{ groups['openhpc_enable_control_True'] + groups['openhpc_enable_batch_True'] }}"
  listen:
    - Restart slurmd service
    - Restart slurmctld service
  when:
    - openhpc_reconfigure_mode == "soft"
    - "'start' in openhpc_actions"
