---
# This is an example playbook to execute Ansible tests.

- name: Check slurm hostlist
  hosts: testohpc_login
  tasks:
  - name: Get slurm partition info
    command: sinfo -h
    register: sinfo
  - name: 
    assert:
      that: "sinfo.stdout_lines == ['compute*     up 60-00:00:0      0    testohpc-compute-[0,1]']"
